### ISSUE TITLE
Add nuget package for Cyotek Dithering to nuget.org

### ISSUE THREAD

**Issue by mjamro** [cyotek/Dithering#1]
Is there a nuget package for available of Cyotek/Dithering project on any public nuget feed?  I looked through the list of packages on [nuget.org](https://www.nuget.org/profiles/cyotek) but i cannot seem to find one. 

I think it would be useful to have a package containing just the dithering algorithms without the GUI.

**Comment by cyotek** [comment]
Hello,

Currently as you've noticed there's no package, for a variety of reasons. 

In my code, I have those classes linked into my core drawing library; this has everything needed to "just work". 

However, in the demonstration application there's none of that - the classes can't really work "out of the box" as they require another process to give them purpose. The demo does it with a simple black and white color transform, but to make best use of them (for image dithering at least), you'd need some form of quantizer.

A similar issue is that in my own code, I use a custom `ArgbColor` structure so that I can directly manipulate bitmaps via pointers. The demo code includes a bare-bones version of this structure, but that shouldn't be included in a specific "Dithering Library" as its usage scope is far wider than that. At the same time, I'm not really going to create another package for a single structure. I could change the API to use the standard `Color` instead, but then I'm slowing down my code by converting colors which I'd rather avoid.

The final issue is that the API isn't final. By sheer co-incidence, today I have been working on adding [ordered dithering](https://en.wikipedia.org/wiki/Ordered_dithering) to the project. That will probably require changes to the API, at the very least `IErrorDiffusion` is a touch inaccurate for ordered dithering.

So for any and all of the reasons above, there probably won't be a package available in the short term. However, it's only for technical reasons - I have no object to creating a package eventually when I can be sure it will be useful and not conflict or get broken by other dependencies.

Slightly longer reply than I was expect to write, but I hope this helps, if not please let me know.

Regards;
Richard Moss

**Comment by mjamro** [comment]
Thanks for such a comprehensive answer. I was expecting answer like that after closer look at the code, it's more like an awesome demonstrator of different algorithms and not an end-user ready library. I'll continue too look for a different solution than, thanks anyway.
