### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by gingerbeardman** [cyotek/Dithering#2]
I'd love to have a play around with this. Any chance of a binary release? Thanks!

**Comment by cyotek** [comment]
Hello,

Thanks for the interest. This isn't really a tool to use, but a demonstration of concepts. Regardless, I compiled the latest source and it's now present in the Releases section.

I also updated the source as I had a few commits where I was trying to added Bayer dithered. I do like that style but I can't remember why I never finished it... probably hit a brick wall trying to get it to work properly. It's been quite a while since I last changed this source!

Hope the binary helps.

Regards;
Richard Moss

**Comment by gingerbeardman** [comment]
Thanks so much! Yes, I just wanted to have a play with this little toy.

Here's a similar thing I've been working on; I've also not got around to adding Beyer just yet.

https://www.gingerbeardman.com/dither-studio/
